# Generated by Django 5.0 on 2023-12-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
